---
- name: Adiciona chave GPG para o repositório 
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg


- name: Adiciona repo do kubernetes
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present


- name: Instala os pacotes do k8s
  apt:
    update_cache: yes
    name: "{{ item }}"
  loop:
    - kubelet=1.20.4-00
    - kubeadm=1.20.4-00
    - kubectl=1.20.4-00


- name: Hold k8s packages version
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl


- name: Checa se o cluster já foi inicializado
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: st


- name: Init k8s master
  command: kubeadm init --control-plane-endpoint 192.168.33.10
  when: st.stat.exists == false
  register: init_status


- name: Instala o Weavenet CNI
  ansible.builtin.shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  when:
    - init_status is not skipped 
    - init_status is succeeded
  register: cni_status

- name: Remove taint do isolamento do control plane para rodar aplicação no master
  command: kubectl --kubeconfig=~/.kube/config taint nodes --all node-role.kubernetes.io/master-
  when:  
    - cni_status is not skipped 
    - cni_status is succeeded
