apiVersion: v1
kind: Service
metadata:
  name: vagrant-service
  labels:
    app: vagrant-app
spec:
  type: LoadBalancer
  selector:
    app: vagrant-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000