---
# - name: Configura módulos necessários para o containerd
#   blockinfile:
#     path: /etc/modules-load.d/containerd.conf
#     block: |
#       overlay
#       br_netfilter
- name: Configura módulos para o containerd
  copy:
    src: modules-containerd.conf
    dest: /etc/modules-load.d/containerd.conf
    owner: root
    group: root
    mode: 0755


- name: Carrega módulos necessários
  modprobe:
    name: "{{ item }}"
  loop:
    - overlay
    - br_netfilter


- name: Adiciona confs sysctl
  ansible.posix.sysctl:
    sysctl_file: "/etc/sysctl.d/99-kubernetes-cri.conf"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1'}
    - { name: 'net.ipv4.ip_forward', value: '1'}
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1'}


- name: Instala pré-requisitos
  apt:
    update_cache: yes
    name: "{{ item }}"
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common


- name: Adiciona chave GPG para o repositório containerd
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg


- name: Adiciona repo do containerd
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present


- name: Instala o containerd
  apt:
    update_cache: yes
    name: "containerd.io=1.4.3-1"


- name: Hold containerd version
  dpkg_selections:
    name: containerd.io
    selection: hold


- name: Copy containerd config file
  copy:
    src: containerd-config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: 0644
  notify: # restarta quando tem mudanca no arquivo /etc/containerd/config.toml
    - Restart containerd service
